services:
  - type: web
    name: trendlens-api
    env: python
    plan: free
    rootDir: .
    buildCommand: pip install -r requirements-lite.txt && bash postbuild.sh
    startCommand: python -m src.api
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10
